package harness

import (
	"context"
	"math/rand/v2"
	"strings"
	"testing"
	"time"
)

// TestRunRefusesAValueDomainOfOne pins a rule the operation generator depends
// on and cannot enforce itself.
//
// A compare-and-swap is generated by drawing `to` and retrying until it differs
// from `from`, because a CAS from a value to itself constrains nothing and
// history.Validate rejects one. With only a single value available the two can
// never differ, so that retry becomes an unbreakable spin - and it is reached
// not at the start of the run but the first time some client comes to believe a
// key holds the only value there is. The run then stops making progress,
// ignores Duration, and leaves its node processes behind. Refusing the
// configuration is the only honest answer, because there is no compare-and-swap
// this domain can express.
func TestRunRefusesAValueDomainOfOne(t *testing.T) {
	// Proxies to nowhere and no faults: nothing is ever dialled successfully,
	// which is all this needs. The configuration is refused before any traffic,
	// so the run never gets far enough for that to matter.
	topo, err := BuildTopology([]string{"127.0.0.1:9"}, false)
	if err != nil {
		t.Fatal(err)
	}
	defer topo.Close()

	cfg := Config{
		Clients: 1, Keys: 1, ValueMax: 1,
		Faults: "none", Duration: 2 * time.Second, Quiesce: time.Millisecond,
	}

	done := make(chan error, 1)
	go func() {
		_, runErr := Run(context.Background(), topo, cfg)
		done <- runErr
	}()
	select {
	case runErr := <-done:
		if runErr == nil {
			t.Fatal("Run accepted -value-max 1; the CAS generator can only spin on a domain of one value")
		}
		// Asserting on the message, because this run has other ways to fail and
		// a test that accepts any error would pass while the hang was still there.
		if !strings.Contains(runErr.Error(), "value-max") {
			t.Fatalf("Run failed, but not for the reason under test: %v", runErr)
		}
		t.Logf("refused, as it should be: %v", runErr)
	case <-time.After(30 * time.Second):
		t.Fatal("Run neither refused nor finished on -value-max 1: the to != from retry loop is spinning")
	}
}

// TestGenerateReturnsOnEveryAcceptedDomain guards the other side of the same
// rule: every value domain Run does accept must let that retry terminate.
func TestGenerateReturnsOnEveryAcceptedDomain(t *testing.T) {
	done := make(chan struct{})
	go func() {
		defer close(done)
		rng := rand.New(rand.NewPCG(1, 2))
		keys := []string{"k0", "k1"}
		for _, valueMax := range []int{MinValueMax, 3, 10} {
			// Seed the client's beliefs with every value in the domain, which is
			// what puts `from` on a collision course with `to`.
			for believedValue := 0; believedValue <= valueMax; believedValue++ {
				believed := map[string]int{"k0": believedValue, "k1": believedValue}
				for i := 0; i < 2000; i++ {
					generate(rng, keys, believed, valueMax)
				}
			}
		}
	}()
	select {
	case <-done:
	case <-time.After(30 * time.Second):
		t.Fatal("generate did not return: the to != from retry loop cannot terminate on a domain Run accepts")
	}
}

func TestRunRefusesFewerClientsThanNodes(t *testing.T) {
	// Clients are spread round-robin, so fewer clients than nodes leaves a node
	// with nobody talking to it. A partition then cuts hops that were carrying
	// nothing, the byte counters still look healthy because one seed's client
	// blip contributes, and the run returns a clean verdict about a network
	// that was never meaningfully broken. Measured at one client over three
	// nodes: five clean seeds in which both followers answered four requests
	// each, all of them after the heal.
	topo, err := BuildTopology(deadAddrs(3), true)
	if err != nil {
		t.Fatal(err)
	}
	defer topo.Close()

	_, err = Run(t.Context(), topo, Config{
		Clients:  1,
		Keys:     2,
		Duration: 2 * time.Second,
		Faults:   "partition",
		Seed:     1,
	})
	if err == nil {
		t.Fatal("Run accepted one client across three nodes; two of them would never be asked anything")
	}
	if !strings.Contains(err.Error(), "at least one per node") {
		t.Fatalf("Run refused it as %q, which does not tell the caller what to change", err)
	}
}

func TestRunAcceptsExactlyOneClientPerNode(t *testing.T) {
	// The guard must not be off by one: three clients over three nodes is the
	// smallest configuration in which every node is observed, and it has to be
	// allowed or the harness refuses its own minimum.
	topo, err := BuildTopology(deadAddrs(3), true)
	if err != nil {
		t.Fatal(err)
	}
	defer topo.Close()

	// Nothing is listening behind those addresses, so every operation comes
	// back indeterminate. That is a fine run with a boring history, and the
	// point here is only that the configuration was not refused.
	res, err := Run(t.Context(), topo, Config{
		Clients:   3,
		Keys:      1,
		Duration:  700 * time.Millisecond,
		OpTimeout: 50 * time.Millisecond,
		Faults:    "none",
		Seed:      1,
		Quiesce:   50 * time.Millisecond,
	})
	if err != nil {
		t.Fatalf("Run refused one client per node: %v", err)
	}
	if len(res.History) == 0 {
		t.Fatal("the run recorded nothing at all")
	}
}

// TestWithDefaultsLeavesAnImpossibleValueAlone pins the distinction the rest of
// this fix rests on.
//
// A blank field means "choose for me", and WithDefaults chooses. A negative one
// is a value somebody typed, and no default it could substitute is what they
// asked for. WithDefaults used to treat everything <= 0 as blank, so
// `-duration -5s` ran for eight seconds under a banner that echoed -5s back at
// the person who typed it. Keeping the negative here is what lets Validate say
// so a line later.
func TestWithDefaultsLeavesAnImpossibleValueAlone(t *testing.T) {
	c := Config{
		Clients:   -1,
		Keys:      -1,
		Duration:  -5 * time.Second,
		OpTimeout: -400 * time.Millisecond,
		ThinkMax:  -3 * time.Second,
		Quiesce:   -time.Second,
		ValueMax:  -2,
		MaxOps:    -1,
	}.WithDefaults()

	for _, f := range []struct {
		name string
		got  int64
		want int64
	}{
		{"Clients", int64(c.Clients), -1},
		{"Keys", int64(c.Keys), -1},
		{"Duration", int64(c.Duration), int64(-5 * time.Second)},
		{"OpTimeout", int64(c.OpTimeout), int64(-400 * time.Millisecond)},
		{"ThinkMax", int64(c.ThinkMax), int64(-3 * time.Second)},
		{"Quiesce", int64(c.Quiesce), int64(-time.Second)},
		{"ValueMax", int64(c.ValueMax), -2},
		{"MaxOps", int64(c.MaxOps), -1},
	} {
		if f.got != f.want {
			t.Errorf("WithDefaults replaced %s = %d with %d; the caller asked for something impossible and is entitled to be told, not overruled",
				f.name, f.want, f.got)
		}
	}
}

// TestValidateRefusesWhatNoCallerCanMean walks every value Validate exists to
// catch, and checks that Run refuses it in the same words rather than running
// something else.
func TestValidateRefusesWhatNoCallerCanMean(t *testing.T) {
	base := Config{
		Clients:   1,
		Keys:      1,
		Duration:  time.Second,
		OpTimeout: 50 * time.Millisecond,
		ValueMax:  8,
		Faults:    "none",
		Quiesce:   time.Millisecond,
	}
	// If the base were already invalid the table below would pass for the
	// wrong reason, so it is checked first.
	if err := base.Validate(); err != nil {
		t.Fatalf("the base configuration of this test is itself refused: %v", err)
	}

	// One node, and nothing listening behind it. No case here gets far enough
	// to dial anything.
	topo, err := BuildTopology([]string{"127.0.0.1:9"}, false)
	if err != nil {
		t.Fatal(err)
	}
	defer topo.Close()

	cases := []struct {
		name   string
		impose func(*Config)
	}{
		{"duration", func(c *Config) { c.Duration = -5 * time.Second }},
		{"op-timeout", func(c *Config) { c.OpTimeout = -time.Millisecond }},
		{"think", func(c *Config) { c.ThinkMax = -3 * time.Second }},
		{"quiesce", func(c *Config) { c.Quiesce = -time.Second }},
		{"clients", func(c *Config) { c.Clients = -1 }},
		{"keys", func(c *Config) { c.Keys = -1 }},
		{"value-max", func(c *Config) { c.ValueMax = 1 }},
		{"max-ops", func(c *Config) { c.MaxOps = -1 }},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			cfg := base
			c.impose(&cfg)

			err := cfg.Validate()
			if err == nil {
				t.Fatalf("Validate accepted a %s no caller can have meant", c.name)
			}
			// Naming the field is the point. A refusal that does not say which
			// value was wrong is barely better than the silent substitution it
			// replaced.
			if !strings.Contains(err.Error(), c.name) {
				t.Fatalf("Validate refused it as %q, which never names %s", err, c.name)
			}

			_, runErr := Run(t.Context(), topo, cfg)
			if runErr == nil {
				t.Fatalf("Run accepted what Validate refused (%v)", err)
			}
			if runErr.Error() != err.Error() {
				t.Fatalf("Run refused it as %q; Validate says %q, and a caller reading the second should recognise the first", runErr, err)
			}
		})
	}
}

// TestABlankConfigIsStillAWorkingOne is the library caller's side of the
// bargain. Config{} means "choose everything for me", and it has to keep
// meaning that: the fix is about values somebody chose, not about making
// callers spell out fields they never cared about.
func TestABlankConfigIsStillAWorkingOne(t *testing.T) {
	c := Config{}.WithDefaults()
	if err := c.Validate(); err != nil {
		t.Fatalf("a blank configuration came out of WithDefaults invalid: %v", err)
	}
	// The pauses especially. Honouring an explicit zero must not turn every
	// default run into a hot loop with no settling period before the final
	// reads - which are the most informative operations in the history.
	if c.ThinkMax <= 0 {
		t.Error("a blank ThinkMax was left at zero; clients would never pause and intervals would stop overlapping")
	}
	if c.Quiesce <= 0 {
		t.Error("a blank Quiesce was left at zero; the run would have no uncontended final reads")
	}
}

// TestAnExplicitZeroPauseSurvivesDefaults is the other half: a caller who does
// mean zero gets zero. This is the case a careless fix breaks, because zero is
// also what a blank field looks like.
func TestAnExplicitZeroPauseSurvivesDefaults(t *testing.T) {
	c := Config{ThinkMaxSet: true, QuiesceSet: true}.WithDefaults()
	if c.ThinkMax != 0 {
		t.Errorf("ThinkMax = %s; the caller said zero and was given a default instead", c.ThinkMax)
	}
	if c.Quiesce != 0 {
		t.Errorf("Quiesce = %s; the caller said zero and was given a default instead", c.Quiesce)
	}
	if err := c.Validate(); err != nil {
		t.Fatalf("no pause and no settling time is a legitimate run, but Validate refused it: %v", err)
	}
	// Saying "I mean zero" about the pauses must not stop anything else being
	// filled in.
	if c.Clients < 1 || c.Keys < 1 || c.Duration <= 0 || c.OpTimeout <= 0 {
		t.Errorf("the rest of the configuration was left blank: %+v", c)
	}
}
