package harness

import (
	"context"
	"math/rand/v2"
	"strings"
	"testing"
	"time"
)

// TestRunRefusesAValueDomainOfOne pins a rule the operation generator depends
// on and cannot enforce itself.
//
// A compare-and-swap is generated by drawing `to` and retrying until it differs
// from `from`, because a CAS from a value to itself constrains nothing and
// history.Validate rejects one. With only a single value available the two can
// never differ, so that retry becomes an unbreakable spin - and it is reached
// not at the start of the run but the first time some client comes to believe a
// key holds the only value there is. The run then stops making progress,
// ignores Duration, and leaves its node processes behind. Refusing the
// configuration is the only honest answer, because there is no compare-and-swap
// this domain can express.
func TestRunRefusesAValueDomainOfOne(t *testing.T) {
	// Proxies to nowhere and no faults: nothing is ever dialled successfully,
	// which is all this needs. The configuration is refused before any traffic,
	// so the run never gets far enough for that to matter.
	topo, err := BuildTopology([]string{"127.0.0.1:9"}, false)
	if err != nil {
		t.Fatal(err)
	}
	defer topo.Close()

	cfg := Config{
		Clients: 1, Keys: 1, ValueMax: 1,
		Faults: "none", Duration: 2 * time.Second, Quiesce: time.Millisecond,
	}

	done := make(chan error, 1)
	go func() {
		_, runErr := Run(context.Background(), topo, cfg)
		done <- runErr
	}()
	select {
	case runErr := <-done:
		if runErr == nil {
			t.Fatal("Run accepted -value-max 1; the CAS generator can only spin on a domain of one value")
		}
		// Asserting on the message, because this run has other ways to fail and
		// a test that accepts any error would pass while the hang was still there.
		if !strings.Contains(runErr.Error(), "value-max") {
			t.Fatalf("Run failed, but not for the reason under test: %v", runErr)
		}
		t.Logf("refused, as it should be: %v", runErr)
	case <-time.After(30 * time.Second):
		t.Fatal("Run neither refused nor finished on -value-max 1: the to != from retry loop is spinning")
	}
}

// TestGenerateReturnsOnEveryAcceptedDomain guards the other side of the same
// rule: every value domain Run does accept must let that retry terminate.
func TestGenerateReturnsOnEveryAcceptedDomain(t *testing.T) {
	done := make(chan struct{})
	go func() {
		defer close(done)
		rng := rand.New(rand.NewPCG(1, 2))
		keys := []string{"k0", "k1"}
		for _, valueMax := range []int{minValueMax, 3, 10} {
			// Seed the client's beliefs with every value in the domain, which is
			// what puts `from` on a collision course with `to`.
			for believedValue := 0; believedValue <= valueMax; believedValue++ {
				believed := map[string]int{"k0": believedValue, "k1": believedValue}
				for i := 0; i < 2000; i++ {
					generate(rng, keys, believed, valueMax)
				}
			}
		}
	}()
	select {
	case <-done:
	case <-time.After(30 * time.Second):
		t.Fatal("generate did not return: the to != from retry loop cannot terminate on a domain Run accepts")
	}
}

func TestRunRefusesFewerClientsThanNodes(t *testing.T) {
	// Clients are spread round-robin, so fewer clients than nodes leaves a node
	// with nobody talking to it. A partition then cuts hops that were carrying
	// nothing, the byte counters still look healthy because one seed's client
	// blip contributes, and the run returns a clean verdict about a network
	// that was never meaningfully broken. Measured at one client over three
	// nodes: five clean seeds in which both followers answered four requests
	// each, all of them after the heal.
	topo, err := BuildTopology(deadAddrs(3), true)
	if err != nil {
		t.Fatal(err)
	}
	defer topo.Close()

	_, err = Run(t.Context(), topo, Config{
		Clients:  1,
		Keys:     2,
		Duration: 2 * time.Second,
		Faults:   "partition",
		Seed:     1,
	})
	if err == nil {
		t.Fatal("Run accepted one client across three nodes; two of them would never be asked anything")
	}
	if !strings.Contains(err.Error(), "at least one per node") {
		t.Fatalf("Run refused it as %q, which does not tell the caller what to change", err)
	}
}

func TestRunAcceptsExactlyOneClientPerNode(t *testing.T) {
	// The guard must not be off by one: three clients over three nodes is the
	// smallest configuration in which every node is observed, and it has to be
	// allowed or the harness refuses its own minimum.
	topo, err := BuildTopology(deadAddrs(3), true)
	if err != nil {
		t.Fatal(err)
	}
	defer topo.Close()

	// Nothing is listening behind those addresses, so every operation comes
	// back indeterminate. That is a fine run with a boring history, and the
	// point here is only that the configuration was not refused.
	res, err := Run(t.Context(), topo, Config{
		Clients:   3,
		Keys:      1,
		Duration:  700 * time.Millisecond,
		OpTimeout: 50 * time.Millisecond,
		Faults:    "none",
		Seed:      1,
		Quiesce:   50 * time.Millisecond,
	})
	if err != nil {
		t.Fatalf("Run refused one client per node: %v", err)
	}
	if len(res.History) == 0 {
		t.Fatal("the run recorded nothing at all")
	}
}
